name: extra_care
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  platform: ^3.1.0  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  get: ^4.6.1
  cupertino_icons: ^1.0.0
  qr_code_scanner: ^1.0.0
  smooth_star_rating: ^1.1.1

  firebase_messaging: ^12.0.1
#  firebase_core: ^1.20.0

  flutter_easyloading: ^2.2.1
  intl: ^0.17.0 
  url_launcher: ^6.0.2
  flutter_svg: ^0.19.3
  font_awesome_flutter: ^8.10.0
  barcode_scan2: ^4.2.1
  http: ^0.13.0
  provider: ^5.0.0
  shared_preferences: ^2.0.3
  slide_countdown_clock: ^1.0.3
  email_validator: ^1.0.6
  flutter_screenutil: ^4.0.2+1
  fluttertoast: ^7.1.1
  carousel_slider: ^3.0.0
  image_picker: ^0.7.2
  http_parser: ^4.0.0
  custom_switch: ^0.0.1
  linked_scroll_controller: ^0.1.2
  device_info: ^2.0.0
  video_player: ^2.4.5
  geolocator: ^7.0.1
  extended_image: ^6.2.1
  flutter_local_notifications: ^5.0.0-nullsafety.0
  firebase_core: ^1.0.0
  flutter_verification_code_input:
    git:
      url: https://github.com/tiny-express/flutter_verification_code_input.git



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - lib/lang/en.json
   - lib/lang/ar.json
   - assets/images/scroll.jpg

  fonts:
    - family: Metropolis-Black
      fonts:
        - asset: assets/fonts/Metropolis-Black.otf
          weight: 500
    - family: Metropolis-Thin
      fonts:
        - asset: assets/fonts/Metropolis-Thin.otf
          weight: 500
    - family: Metropolis-ThinItalic
      fonts:
        - asset: assets/fonts/Metropolis-ThinItalic.otf
          weight: 500            
    - family: Metropolis-Bold
      fonts:
        - asset: assets/fonts/Metropolis-Bold.otf 
          weight: 900
    - family: Metropolis-ExtraBold
      fonts:
        - asset: assets/fonts/Metropolis-ExtraBold.otf  
          weight: 900     
    - family: Metropolis-ExtraLightItalic
      fonts:
        - asset: assets/fonts/Metropolis-ExtraLightItalic.otf
          weight: 700
    - family: Metropolis-LightItalic
      fonts:
        - asset: assets/fonts/Metropolis-LightItalic.otf
          weight: 600
    - family: Metropolis-Light
      fonts:
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 500            
    
